### ISSUE TITLE
crash at start

### ISSUE THREAD

**Issue by phate89** [cDima/Aerial#106]
Hi.. I have a weird error with this screensaver.
I followed the readme to install it and it gets added to the list but it doesn't start. the screen flash to the black and returns normal and I can't open screensaver settings. So I checked in appdata\Local and I saw there was no Aerial folder but there was a folder CrashDumps with several Aerial.scr.***.dmp.
So I downloaded the source code to test it in vs 2015 and debug it but I got a weird error. At start (before it loads every code) directly in  _corexemain I get a System.ArgumentException in mscorlib.dll with message (translated by me from italian): The path can't be an empty string or composed by only spaces.
Do you have any idea what might trigger this error?

**Comment by alistairmcmillan** [comment]
@phate89 Could you try v5.1 for me? Does that have the same error?

**Comment by phate89** [comment]
v5.1 works

**Comment by alistairmcmillan** [comment]
:( Might be my fault then.

Could you attach one of the dmp files here please?

**Comment by phate89** [comment]
sure here it is

**Comment by phate89** [comment]
sure here it is 
[Aerial.scr.13456.zip](https://github.com/cDima/Aerial/files/744732/Aerial.scr.13456.zip)

**Comment by alistairmcmillan** [comment]
@phate89 Could you attach a screenshot of the Aerial Settings dialog from the latest version please?

**Comment by phate89** [comment]
with the latest version I can't open settings at all

**Comment by alistairmcmillan** [comment]
@phate89 Are you familiar with Regedit? Could you show us the values you have under `HKEY_CURRENT_USER\Software\AerialScreenSaver` on your PC?

**Comment by phate89** [comment]
I don't have that at all..

**Comment by alistairmcmillan** [comment]
@phate89 I'm confused then. If you've run any version of the screensaver that key should exist.

How about something like `HKEY_USERS\S-1-5-21-1229272821-231175127-839231175-135808\Software\AerialScreenSaver`? The long GUID number will be different but if you open regedit there should only be one or two so it shouldn't be difficult to locate yours.

**Comment by phate89** [comment]
I searched in the regedit and I didn't find anywhere the reg key.. Yes v5.1 works but no reg key

**Comment by alistairmcmillan** [comment]
@phate89 I'm not having much success trying to recreate the problem you're having.

Do you have .Net Framework 4.6 installed? https://www.microsoft.com/en-us/download/details.aspx?id=48130

**Comment by alistairmcmillan** [comment]
@phate89 Are you running a preview version of Windows 10?

**Comment by phate89** [comment]
I use windows 10 stable with the latest udpate so net framework 4.6 is included and I have it installed..

**Comment by phate89** [comment]
This is really weird.. I wasn't able to compile (both 5.1 and 6.0) or make work the 6.0 version but now everything works (20 minutes ago I checked again and 6.0 still wasn't working).. No Idea what changed.. I tried to use dependency walker to see if there was some problem in the dll linked and compile 5.1 with x86 processor destination but I don't think that might fixed something since now it compiles also with "any cpu".. Now I also have regedit keys.. weird.. Thanks for your help anyway. Great screensaver :)

**Comment by cDima** [comment]
@phate89 a new version 6.1 is out with a small fix;
I compile the version for all as "Any CPU" and "All" configuration. For debugging, this is switched to "x86" and "Debug". If you have the same debugging issues, lets write up a readme about dev setup as to help others. Glad it magically started working for you. :)
