### ISSUE TITLE
Does not display, saves crash files

### ISSUE THREAD

**Issue by keithdtyler** [cDima/Aerial#107]
The app is crashing whenever I hit Preview or Settings. Running the EXE also doesn't work. Simply nothing happens. When you click Preview the little display in the dialog shows the desktop for a second, then blank again.

Windows 10 Pro 64-Bit
MS Surface Pro 4
16GB
Intel Iris Graphics 540

Example crash file output:

Version=1
EventType=CLR20r3
EventTime=131306416988624025
ReportType=2
Consent=1
UploadTime=131306416990030025
ReportIdentifier=d2fddb89-ea70-11e6-aa2b-985fd3439a31
IntegratorReportIdentifier=6f69918d-5983-4a06-92a4-40dcd0cd4d27
NsAppName=Aerial.scr
AppSessionGuid=00001f24-0001-0011-819c-4c957d7ed201
TargetAppId=W:000675703215f50c2c8ab430f3d4514227a300000000!00004bff6b2b75b3dc75ebee4faf8923b0a04827ccf5!Aerial.scr
TargetAppVer=2017//02//01:02:30:13!0!Aerial.scr
BootId=4294967295
Response.BucketId=1ae48253c3aef28c470224b48f16431c
Response.BucketTable=5
Response.LegacyBucketId=129352056523
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=Aerial.scr
Sig[1].Name=Problem Signature 02
Sig[1].Value=1.0.0.0
Sig[2].Name=Problem Signature 03
Sig[2].Value=58914835
Sig[3].Name=Problem Signature 04
Sig[3].Value=mscorlib
Sig[4].Name=Problem Signature 05
Sig[4].Value=4.6.1586.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=575a1530
Sig[6].Name=Problem Signature 07
Sig[6].Value=15f9
Sig[7].Name=Problem Signature 08
Sig[7].Value=25
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.ArgumentException
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.14393.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=26bd
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=26bd67984cfc4a9fe765e54265973563
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=0202
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=020278731a97c8f76734a779984178c9
UI[2]=C:\WINDOWS\Aerial.scr
UI[3]=ScreenSaver has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\WINDOWS\Aerial.scr
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\sechost.dll
LoadedModule[8]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[9]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[10]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[11]=C:\WINDOWS\System32\combase.dll
LoadedModule[12]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[13]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[14]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[15]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[16]=C:\WINDOWS\System32\USER32.dll
LoadedModule[17]=C:\WINDOWS\System32\win32u.dll
LoadedModule[18]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[19]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[21]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[22]=C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[23]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\e96b4590c579d08edc2e60cc3e5ae997\mscorlib.ni.dll
LoadedModule[24]=C:\WINDOWS\System32\ole32.dll
LoadedModule[25]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[26]=C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll
LoadedModule[27]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[28]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[29]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[30]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System\ee1c3ea3e0049df6d53b35e21c2247e4\System.ni.dll
LoadedModule[31]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Drawing\3ac58fb7cb8d849d0f85f2435e1a0066\System.Drawing.ni.dll
LoadedModule[32]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\04e26b57f0c211fdb0d877810b37497f\System.Windows.Forms.ni.dll
LoadedModule[33]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=ScreenSaver
AppPath=C:\WINDOWS\Aerial.scr
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=4B60621D05F754BBA9540BE2E8B5C891
MetadataHash=1374309679

**Comment by cDima** [comment]
Thanks for the report, I'll need to design a error log into the app to give me more details on the crash.
If you have Visual Studio, launching the app may show the actual error.

**Comment by cDima** [comment]
Also, if there is anything in the event log, it may show the actual error.

**Comment by alistairmcmillan** [comment]
@cDima @keithdtyler I think I've worked out what's happening. Only seems to affect Windows 10 64bit. Just doing a little testing then I'll send a PR.

**Comment by cDima** [comment]
@alistairmcmillan awesome, a bit strange since I'm on Win 10 64 bit, but I trust you. :)

**Comment by alistairmcmillan** [comment]
@cdima Actually affects all versions of Windows, not just 64-bit.

Basically if the registry key didn't exist it was trying to create a directory called "". My fault. Sorry. :)

**Comment by cDima** [comment]
Looks like it's fixed, I'll push a new version v6.1 in a bit, please check @keithdtyler 
Thanks @alistairmcmillan
