### ISSUE TITLE
"Windows Media Player cannot play this file..."

### ISSUE THREAD

**Issue by kamilmirza** [cDima/Aerial#121]
today i left my screen and came back and saw this error:
![explorer_2017-04-15_19-30-43](https://cloud.githubusercontent.com/assets/6561475/25074456/6a6c6c56-2314-11e7-960d-b960e95dcb71.png)
cannot preview the cached ones and clearing cache didn't helped either
even removed and reinstalled the Windows Media Player from Windows features, with restarts
have not experienced any issues with Aerial earlier with the same build
windows 10 v1607 build 14393.rs1

**Comment by wuyanxu** [comment]
Me too

**Comment by Gladrat** [comment]
Same problem here.
Reinstalling screensaver and reinstalling Media Player dosen't help.

Seems like the problem dosen't happen when i check the "Play different Aerial on each monitor".
@kamilmirza or @wuyanxu can u test this ?

**Comment by kamilmirza** [comment]
@Gladrat
I'm using without "Play different Aerial on each monitor"
and the problem was fixed after I updated my codecs using K-Lite Codec Pack

**Comment by alistairmcmillan** [comment]
Closing as @kamilmirza says their problem was fixed.
