### ISSUE TITLE
Request - Change default download folder

### ISSUE THREAD

**Issue by TTC1** [cDima/Aerial#125]
The current video files are downloaded into C:\Users\YOURUSERNAME\AppData\Local\Aerial
And it is, as of May 31st 2017, about 10GB heavy.
I'm on Win10 installed on a 128GB SSD and I keep on running out of free disk space on my C:

It would be very convenient to be able to manually select where the videos are to be nested.
I have a few TBs free in my other drives, it would be more practical to have the videos download onto another folder that is not on C:.

Thanks for your work and to evaluate my request.
Cheers.

**Comment by alistairmcmillan** [comment]
@TTC1 Please try the latest release. It allows you to change the location of the cache folder.

https://github.com/cDima/Aerial/releases/tag/v6.1

Please note, once you pick a new location it is up to you to move the videos that have already been cached. The screensaver won't automatically move them for you. :)
