### ISSUE TITLE
Not working anymore on Windows 10 creators update

### ISSUE THREAD

**Issue by samhtht** [cDima/Aerial#127]
Hi,

since I upgraded to Windows 10 creators update, the screensaver won't display anymore. I am also not able to preview it anymore in screensaver settings. It was working fine before.
My config is dell xps 9560 + 2 external monitors

**Comment by kevinvangelder** [comment]
As of creators update, old-style screen savers are not supported. You can run the screen saver program manually but it can't be configured to run automatically.

**Comment by alistairmcmillan** [comment]
@kevinvangelder They just moved the settings.

You can find them under:
`Settings > Personalization > Lock screen > Screen saver settings`

**Comment by kevinvangelder** [comment]
Pretty sure that option was not there on my Creators Update machine when I was looking at it last night.

**Comment by alistairmcmillan** [comment]
@kevinvangelder Just checked there on a Windows 10 machine with the Creators Update installed. It's still there.

**Comment by alistairmcmillan** [comment]
@samhtht I just tested the screensaver extensively in Windows 10 Creator Update. It works fine.

Do you get any error messages?

Are you running [the latest version]( https://github.com/cDima/Aerial/releases/tag/v6.1)?

Do you have the videos cached?

**Comment by alistairmcmillan** [comment]
No reply. Closing.
