### ISSUE TITLE
Scaling of screensaver

### ISSUE THREAD

**Issue by devbeard** [cDima/Aerial#13]
It would be great to have some scaling options for the videos (`No scale/Stretch/Fill`). I have black bars on every side of the video on a `3440x1440` display and would opt to have the video fill my screen (aka no black bars).

**Comment by alistairmcmillan** [comment]
Which version of Windows are you running?

**Comment by devbeard** [comment]
Windows 10 Pro 64-bit

**Comment by rreynier** [comment]
Same here, running 2560 by 1600 with windows 10 64bit. It would be nice to stretch to the screensize.

**Comment by alistairmcmillan** [comment]
Duplicate of #12

**Comment by devbeard** [comment]
Had a look at this last night, and I have created a pull request that does screen filling by default. People with 16:9 screens should not notice anything different as the videos from Apple are 16:9, but 21:9, 4:3, 3:2 and others should see it filling out (at the cost of normal video scaling in Windows Media Player).

**Comment by cDima** [comment]
Thanks @devbeard - your request fixed issue #2.
