### ISSUE TITLE
Windows Media Player is not present in Fall Creators Update of Windows 10.

### ISSUE THREAD

**Issue by MurasakiOokamiRyuu** [cDima/Aerial#147]
Hello!
Before anything, thanks so much for this screensaver, i really love it!
But, i'm running the RTM version of Windows 10 Fall Creators Update (Microsoft released them to Windows Insiders first, Version 1709, [16299.15] ) and the Windows Media Player was removed, and is not re-installable through Windows Features. Tried copy Windows Media player from friend's PC, but didn't worked, tried QuickTime but that didn't worked too. I didn't know how to help, i'm just writing this to let you know about this thing in that new update from Windows 10. 
And again, thanks for this screensaver!
(and sorry for any misspelling, im Brazilian, english is not my first language)

**Comment by alistairmcmillan** [comment]
@MurasakiOokamiRyuu Try the suggestion here: https://superuser.com/a/1200000/4018

**Comment by MurasakiOokamiRyuu** [comment]
@alistairmcmillan "The update cannot be applied to your computer"
![image](https://user-images.githubusercontent.com/32534406/31258556-4c1a2b88-aa16-11e7-8e8f-7a5f4e36622c.png)

**Comment by MurasakiOokamiRyuu** [comment]
Some days after, Microsoft released a way to reinstall the Windows Media Player in Fall Creators Update:
Settings > Apps > Apps & Features > Manage optional features > Add a feature > Windows Media Player.

https://betanews.com/2017/10/09/windows-10-update-removes-windows-media-player/
