### ISSUE TITLE
screensaver un playable

### ISSUE THREAD

**Issue by jerrymousse** [cDima/Aerial#152]
![img_1586](https://user-images.githubusercontent.com/33383354/32410561-2b66bdf4-c1bb-11e7-8dbd-70615842d5c2.JPG)

macbook pro 2017, high sierra 10.13.1
aireal wallpaper not working, showing that (the screen in the image) everytime, tried to preview and re-download but no luck, any idea? maybe because of h.265? supporting issues? or is it just my computer's problem?

**Comment by alistairmcmillan** [comment]
@jerrymousse Wrong project. This is the Windows version. That said, the problem seems to be with Apple's High Sierra drivers for Intel chips. For the moment a workaround is to tick the "Show with clock" option. More discussion here https://github.com/JohnCoates/Aerial/issues/377

**Comment by jerrymousse** [comment]
opps, thanks for the reply anyways, saved my life, was kinda frustrated
