### ISSUE TITLE
Contains Ikarus trojan

### ISSUE THREAD

**Issue by evancodergit** [cDima/Aerial#165]
<img width="566" alt="aerial" src="https://user-images.githubusercontent.com/39387911/40203110-54ba6a88-5a78-11e8-95c0-1cd0c4b1bca3.PNG">

**Comment by cDima** [comment]
There were a lot of false positives from anti-viruses for .scr that connect
the internet. A few years back we sent the .exe for analysis to many
vendors and they whitelisted the app. Please submit this app to the
anti-virus so they can mark it as non-ad-ware.

**Comment by alistairmcmillan** [comment]
Ikarus says clean now.

https://www.virustotal.com/#/file/d38694467ed998ce1fa3d352c1fd1fe456cde8738e99566e4cd6a470524bffcc/detection
