### ISSUE TITLE
Video not scaling

### ISSUE THREAD

**Issue by seanhak** [cDima/Aerial#2]
Please add option scale video (cover, contain and no-resize), i get letterboxes around the video on all sides.
Windows 10, Screen res 2560x1440.

Thanks!

**Comment by viktorx11** [comment]
same: scaling would be nice. 
have a notebook with 2 more displays. looks good on notebook, but letterboxes on two displays.. 
may be an option to run screensaver just on the primary screen and let others black would be usefull also.

**Comment by piyush1911** [comment]
Yes, the Resolution detection for the monitors would be awesome to have.
I am getting only 1080p on my display's.

**Comment by cDima** [comment]
Sorry I need a better screen to test, I only have silly 1080p.

**Comment by alistairmcmillan** [comment]
Test screensaver with potential fix for black bars.

https://github.com/alistairmcmillan/Aerial-Windows/releases/tag/untagged-52c1c71367e93d9deacf

Feel free to test. I was only able to test in a couple of virtual machines and it seemed to work okay there. Haven't had the chance to test in a multiple monitor situation (will be able to tomorrow if no-one beats me to it), so I'd be curious to see how it performs there.

**Comment by viktorx11** [comment]
link not working

**Comment by seanhak** [comment]
@alistairmcmillan Link's not working, but you are right regarding the scaling.

AXWMP.stretchToFit are only for web embeds? 
https://msdn.microsoft.com/en-us/library/windows/desktop/dd562467(v=vs.85).aspx

How about using VLC.net, since windows 8+ requires you to buy WMP right (I remember I had to apply for serial key which was free for limited time)?
https://github.com/ZeBobo5/Vlc.DotNet

**Comment by cDima** [comment]
Should be fixed in this second release, thanks team.

**Comment by cDima** [comment]
@seanhak raise a new issue with a VLC branch; we need to confirm win8 doesn't have WMP with it for free before switching to a new video player.

**Comment by seanhak** [comment]
@cDima Will not raise issue for VLC branch. WMP is free, dvd playback and WMC(media center) was the one you had to pay for, which won't affect this product. Sorry for any confusion I raised. Thanks
