### ISSUE TITLE
Dual monitor setup: One is occasionally going dark

### ISSUE THREAD

**Issue by pkornilov** [cDima/Aerial#21]
Hi there. I'm having an issue using my dual monitor setup on Windows 7. The multiple display mode is set to extension (namely "Extend these displays"). Sometimes when I run the screensaver only one of the displays (and it's always a different one) is showing the aerial while the other one is just going dark. Is there a relevant solution to this issue? Thanks

**Comment by cDima** [comment]
@pkornilov I'm guessing this is an internet-load related issue, where one of the media players isn't loading the screensaver correctly. Please let me know how to reproduce, otherwise this is closed for now.
