### ISSUE TITLE
Simply doesn't work...

### ISSUE THREAD

**Issue by HaruMatsu9124** [cDima/Aerial#216]
I tried all stuff in FAQ and also tried using previous versions but never works.
When I click preview in the menu it just shows the black screen and exits after three seconds or so. Yes I have Net flamework thing and Windows Media Player. I don't have any antivirus software and I'm running Windows 10. I also tried running .scr or .exe as admin but same black screen.
Whyyy? Because on my previous laptop it worked and I loved it but when I switch devises it never works somehow...
Please help. Thanks.

**Comment by tassoman** [comment]
I've just added the scr in the windows directory. Works flawless. 
Maybe you have some network issue or antivirus blocked scr file
