### ISSUE TITLE
Finally, found the reason why i got a black screensaver

### ISSUE THREAD

**Issue by heeroyuyj** [cDima/Aerial#24]
as u mentioned, this scr need WMP, so it can function properly

I did find if I disable AMD Crossfire, the WMP play fine, and so the scr (if I enable Crossfire, WMP occurr errors with playing any video files)

anyway, im happy i can use this scr at last...

also, Aerial Screensaver for Mac got "Caching Support & Offline Mode - Beta"

can we have it on windows?

**Comment by alistairmcmillan** [comment]
Caching request duplicate of #11

**Comment by alistairmcmillan** [comment]
And solution for #22
