### ISSUE TITLE
McAfee VirusScan Enterprise detects & deletes Aerial.scr as Artemis!45E318138285 (Trojan)

### ISSUE THREAD

**Issue by wchow77** [cDima/Aerial#28]
On Monday, 11/16/2015, McAfee VirusScan Enterpise 8.8  with DAT 7986.0000 (Nov. 15, 2015) detected Aerial.scr as Artemis!45E318138285 (Trojan) and deleted it.

C:\Windows\System32\SettingSyncHost.exe	C:\Users\user\downloads\aerial.scr	Artemis!45E318138285 (Trojan)

**Comment by cDima** [comment]
"Artemis is the name McAfee Labs gives to unknown, possible risks." - another faulty report.

**Comment by cDima** [comment]
Dup #9
