### ISSUE TITLE
SOLVED: Generates additional .wpl files in Playlists folder

### ISSUE THREAD

**Issue by WalterEagle** [cDima/Aerial#31]
Excellent screensaver, runs really well on Win 10.
However using it appears to create a folder named Playlists with multiple .wpl files, all named in a similar form: Aerial (x).wpl, or Aerial (xx).wpl  where 'x' is an ascending number.
I don't mind the creation of this Playlists folder and files but I don't appear to have any choice over *where* the folder is created. On my PC it gets created inside another folder I use exclusively for MP3 albums. My audio software picks up the .wpl files and tries to list them as playlists which I do not want.

Is the location of this Aerial folder something I can already control (but haven't understood how) or could it be made an option in future releases?

Thank you and regards

**Comment by cDima** [comment]
@WalterEagle if you open the windows media player - are there duplicated Aerial playlists as well?

**Comment by WalterEagle** [comment]
Wow - thank you for such a prompt response!
There is no evidence in Windows Media Player of these Aerial (x).wpl files. But I don't use Windows Media Player as my regular audio or video software.
My MP3 folder is located as G:\MP3s\[ARTISTNAME]\[ALBUMNAME]\...
The Playlists folder I mentioned gets created at G:\MP3s\Playlists
I have SONOS server software installed that continuously scans G:\MP3s for music files and it was through that I first became aware of the Aerial (x).wpl files.
I can see them using Windows Explorer. I can delete the folder and files, but when I reinstall the .scr the folder and files get recreated.

Thanks again

**Comment by WalterEagle** [comment]
Update:
Your question made me try some further experiments and I think I may have established the control I wanted. In Windows Media Player, in the More Options ... choice and Rip Music tab, the destination had somehow been set for G:\MP3s. I don't recall having set this, but I'll accept the blame anyway - it's my PC.
I changed to destination location to another drive and folder and then reinstalled your Aerial.scr. The same Playlists folder and .wpl files now get generated in the new location.
That's fine by me, I just did not want them among my regular music files.
Thank you for the hint about WMP - I would never have thought of checking there.

Thanks and regards.

**Comment by bytehead-** [comment]
I'm not really sure why these files are created.  This is the content of the files.

   <?wpl version="1.0"?>
    <smil>
        <head>
            <meta name="Generator" content="Microsoft Windows Media Player -- 12.0.7601.18840"/>
            <meta name="ItemCount" content="0"/>
            <title>Aerial</title>
        </head>
    </smil>

Talk about effectively zero content in a file.

**Comment by cDima** [comment]
Duplicate #19 fix coming.

**Comment by cDima** [comment]
@WalterEagle @WalterEagle please try the latest build v3 in https://github.com/cDima/Aerial/tree/master/install - it doesn't use playlists but should cycle through the videos well.

**Comment by WalterEagle** [comment]
@cDima - thank you again. I'll try this V3 later today when I'm back at my usual PC. 

@bytehead - I had previously (before your post) looked at the content of one of the .wpl files generated on my PC. It contained a number of URLs which led to the actual movie files used by the screen savers. I downloaded one of these and got all 275MB which subsequently played faultlessly in VLC, WMP and any other video player I tried.

**Comment by bytehead** [comment]
![wtthll](https://cloud.githubusercontent.com/assets/754921/11238523/99bed2d8-8de6-11e5-8ca4-f768b00888d0.gif)

**Comment by bytehead-** [comment]
Sorry, @bytehead .  :laughing:

**Comment by WalterEagle** [comment]
@bytehead-
@bytehead 

Ooops - my bad *<slaphead>*
These pesky minus signs, always been my downfall.

**Comment by WalterEagle** [comment]
@cDima 
Update on V3 after a few hours testing.
Seems to have fixed the issue completely. No trace of any new .wpl files being created or stored anywhere. Excellent service - thank you very much.

**Comment by cDima** [comment]
@WalterEagle thanks, closing.
