### ISSUE TITLE
McAfee

### ISSUE THREAD

**Issue by adriantyndale** [cDima/Aerial#33]
My antivirus software warns me strongly against installing your software.  Do you have any comment on this?

Kind regards

**Comment by alistairmcmillan** [comment]
This is a false positive. There is nothing malicious about the file. Further discussion here #9 and here #25.

**Comment by cDima** [comment]
@adriantyndale my comment is that you should sue your antivirus for misrepresenting software as malware, and they should loose your business.

**Comment by adriantyndale** [comment]
Dear Sir,Thank you for your response to my query.  Much appreciated.Kind regards,Adrian Tyndale


Sent from Samsung Mobile on O2

-------- Original message --------
