### ISSUE TITLE
Feature Request: .exe that plays videos

### ISSUE THREAD

**Issue by piotrowski** [cDima/Aerial#35]
It would be great to have a normal resizable program window, maybe e fullscreen button, so you can watch them on second monitor while working on first one.

**Comment by cDima** [comment]
Cool idea. Any thoughts on UI for picking what to watch? Next/previous, downloaded, favorites as in the original mac screensaver?

**Comment by piotrowski** [comment]
Start with 'just show random one in a program window' for a first version, then add stuff later.

I would prioritize additional features in this order:

1. Fullscreen
2. Next/prev
3. Favorites

But you probably will be getting requests here as soon as it is released ;)

**Comment by cDima** [comment]
Please take a look at the latest build, it has a `/w` flag that shows a windowed interface with aerial videos inside. It's resizable and has a close button for now.

**Comment by piotrowski** [comment]
`aerialv2.exe /w`? That looks very nice already :) Even maximizing the windows already works.

Feedback (Win 10):
* Videos hangs quite often on Fullscreen, seems to be a "focus" problem. Clicking the window fixes it often.
* Sometimes the task bar is visible over the fullscreen window
* Fullscreen gets lost on video change in fullscreen
* Change betweens videos is quite abrupt and a black screen (buffering?)

On to the rest oft the features ;)

Add this to the feature list:
* No taskbar icon, only systray

Seriously, you just made this late night coding session so much better with this build :)

**Comment by piotrowski** [comment]
So 3.1 is out with "Bug fixes and new window move via /w flag!". How does the `/w` flag work on the `.scr` file? Just creating a shortcut and adding the /w behind the path didn't work for me.

**Comment by cDima** [comment]
@piotrowski the `/w` flag would work only on the .exe, a .scr is actually just a renamed .exe. Please rename to .exe and the /w flag should work. The video sometimes freezes for me still, the visible task-bar issue should be fixed, other issues to be addressed.

**Comment by piotrowski** [comment]
@cDima Yep, renaming to .exe fixed it. Funny that Windows seems to do special stuff to `.scr` files...
