### ISSUE TITLE
Feature request - Dreamscene

### ISSUE THREAD

**Issue by bhumitra** [cDima/Aerial#38]
Any way we can use this as a desktop wallpaper (like dreamscene we had for windows 7)

**Comment by jackmawer** [comment]
DreamScene was for vista, and the stuff that's available to replace it is either too buggy to use, commerical or VLC. Not likely, unfortunately.

**Comment by cDima** [comment]
I don't think it's possible to have video as a desktop background in Win10+, although it'd be awesome.
