### ISSUE TITLE
Let users choose which screens to display video on. 

### ISSUE THREAD

**Issue by deucks** [cDima/Aerial#4]
Triple monitor setups have problems with keeping a steady framerate

**Comment by cDima** [comment]
And the other screens should go black?

**Comment by deucks** [comment]
that would be a good way to fix it, although im also wondering if there is a way of reducing the video stream resolution?

**Comment by Amiral-Adamas** [comment]
I can confirm it : My 3 screen resolution (2 1980*1020 and 1 1440*900) as big trouble keeping a steady framerate. Most of the time, the screen is black for 10 seconds while buffering the screensaver, which looks ugly.

**Comment by cDima** [comment]
I suppose I can make a default option to disable all but the primary screens on 3+ screen setups.

**Comment by cDima** [comment]
Added settings for 3+ screens that disabled all but the first video screen, it's on by default.

**Comment by viktorx11** [comment]
is it possible to change the setting to <"all screens" or "Primary screen"> for a setup of 2+ Screens?
actually The 1st Screen is chosen, but not the primary one. In my case the first screen is the small one on my laptop... I would prefer one of my external monitors would show the screen saver - the primary one which i selected to be primary in display settings, an not that ones which extend the desktop.
thx in advance
