### ISSUE TITLE
Aerial Screensaver Windows 10 Bootcamp

### ISSUE THREAD

**Issue by moose2000** [cDima/Aerial#43]
Hi Dmitry, thanks so much for the screensaver.

I have a Macbook (12") 2015 and have the screen saver running with no issues on OSX.
Via bootcamp I also run the machine with Windows 10.
I am having trouble getting the screensaver to run in windows 10 and have the following error message..
<img width="347" alt="aerial error" src="https://cloud.githubusercontent.com/assets/16314567/11830431/ff484c7e-a3df-11e5-9030-e60fe7faca8b.png">
I have tried all of the suggestions in the FAQ but nothing is working.
Any help to resolve this would be hugely appreciated as I would love to have them running in windows.
Many thanks
Charlie

**Comment by cDima** [comment]
That's something new. No sound device seems to be a media player issue only. Perhaps we can indicate that there is no sound in the video. Thanks.

**Comment by moose2000** [comment]
I thought it might be... I'm imaging that it is an issue perhaps only faced when running it via Bootcamp windows. 
Thanks for the help.
Charlie

**Comment by alistairmcmillan** [comment]
@moose2000 Do any videos play successfully in Windows Media Player in Windows 10 for you?

**Comment by moose2000** [comment]
Videos play using the Films and TV app without trouble. When I start a test video (.avi) in media player I only get the 1st frame and nothing more but the sound is OK. Perhaps I need to update media player...

**Comment by moose2000** [comment]
Hi Dmitry, Alistair,
Just wanted to update you both, Today I received a notification to update Windows 10. Following the update the screen savers work perfectly.
Cheers,

Charlie

**Comment by cDima** [comment]
Cleaning up issues; thanks @moose2000
