### ISSUE TITLE
WMP fails to load videos

### ISSUE THREAD

**Issue by mikeelmasry** [cDima/Aerial#44]
Aerial Screen Saver doesn't work for me. I am running Windows 7 Pro 64bit. I get the following error from WMP: 
![wmp_error](https://cloud.githubusercontent.com/assets/13473638/11857811/9a2e75c6-a410-11e5-8cc4-526160f0956a.jpg)
I tried loading the Aerial.wpl playlist in VLC and it runs fine there so I thought it was a codec issue. I downloaded the codec pack for WMP but still no love. 
![vlc_no_errors](https://cloud.githubusercontent.com/assets/13473638/11857870/f9eb63de-a410-11e5-8b66-736a17303247.jpg)
It could just be a problem with my computer but it would be great if newer versions of Aerial support other media players like VLC.

**Comment by nsnyder** [comment]
I have this issue intermittently. Sometimes it's just one video and then the next one plays, sometimes it's a couple times in a row. But it doesn't seem consistent. (I'll try to get the error the next time I see it).

**Comment by tbourgeo** [comment]
Same here

**Comment by thenamelessthing** [comment]
Same thing for me under Win10

**Comment by cDima** [comment]
@thenamelessthing @tbourgeo Do the screensavers work alright in Windows Media Player or are all of you receiving the same error for the files? Have the codecs on the machine changed from defaults (perhaps vlc installs over some?)

**Comment by thenamelessthing** [comment]
if I click on the scr. It open the screensaver and a windows media player are displayed. How can I open the screensaver in wmp?

**Comment by cDima** [comment]
If it ever worked on your machine longer than 5 mins, you may have the video files cached at `C:\Users\YOURUSERNAME\AppData\Local\Aerial`, or else you can download it [from apple](http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-1.mov).

**Comment by thenamelessthing** [comment]
For me it never worked

**Comment by alistairmcmillan** [comment]
@thenamelessthing How many monitors do you have?

**Comment by thenamelessthing** [comment]
3

**Comment by alistairmcmillan** [comment]
@thenamelessthing Are there any MOV files in C:\Users\YOURUSERNAME\AppData\Local\Aerial or C:\Users\YOURUSERNAME\AppData\Local\Temp?

**Comment by thenamelessthing** [comment]
I will check Monday..

Le 2016-10-14 16:07, "Alistair McMillan" <notifications@github.com> a
écrit :

**Comment by alistairmcmillan** [comment]
@thenamelessthing Are you behind a corporate proxy or firewall? Some people find that their proxy/firewall blocks access to the videos on Apple's CDN servers of choice.

**Comment by thenamelessthing** [comment]
Nothing like that are in place at work..

Le 2016-10-14 16:36, "Alistair McMillan" <notifications@github.com> a
écrit :

**Comment by thenamelessthing** [comment]
> Are there any MOV files in C:\Users\YOURUSERNAME\AppData\Local\Aerial or C:\Users\YOURUSERNAME\AppData\Local\Temp?

Nothing!

**Comment by alistairmcmillan** [comment]
@thenamelessthing What happens if you try to open http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json in a web browser? Do you get a bunch of text?

If that works, what happens if you try to open http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b1-3.mov in a web browser?

**Comment by thenamelessthing** [comment]
First test: I see a bunch of text..
Second test: it download a .mov

**Comment by thenamelessthing** [comment]
It play the file with the movie player included with Win10 not wmp, it is important?

**Comment by alistairmcmillan** [comment]
@thenamelessthing Do you get an error message when you try to play the file in Windows 10 WMP? The files play okay here in Windows 7 WMP but there do seem to be a lot of people asking how to play QuickTime files in Windows 10 WMP so maybe they changed something.

**Comment by thenamelessthing** [comment]
If I try to open the file with "open with" and choose wmp it work!

**Comment by cDima** [comment]
@mikeelmasry @thenamelessthing is the error still showing up in the latest build? v5?

**Comment by thenamelessthing** [comment]
@cDima the error still showing up! ;-(

**Comment by mkracik** [comment]
I was getting the same error message and I have been able to troubleshoot it. The error code is 0xC00D0FEA which means that Windows Media Player can't open a file with unknown/unregistered extension from the web.

It can be easily reproduced in Windows Media Player itself, completely outside of screen saver:
Start Windows Media Player
Choose File/Open URL...
Enter URL http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b2-2.mov
![image](https://cloud.githubusercontent.com/assets/17297517/20651510/ed5755d2-b4b4-11e6-9ae7-6951261aae7c.png)
Result:
![image](https://cloud.githubusercontent.com/assets/17297517/20651511/f3c2df72-b4b4-11e6-99c1-b496f8f92ea2.png)
Windows Media Player encountered a problem while downloading the file.

Downloading the file, saving it locally and opening it in WMP works fine.

I was not able to make it work by registering the extension .mov to Windows Media Player anywhere in Windows 10 Settings/Choose default apps.

A possible solution would be to only show videos already downloaded to local cache which would result in long startup time and loss of streaming.

**Comment by alistairmcmillan** [comment]
Think this was due to partially downloaded MOV files in the cache. The screensaver has been updated to avoid the problem by clearing partial download from the cache's temp folder on startup and only copying files to the cache folder once they are completely downloaded.

**Comment by thenamelessthing** [comment]
Sorry to comment this again but, the problem is still here even witht the latest build.

I have try something different, I have drag the movie file on the Aerial.scr and the screensaver work. But when it's launched from Windows pannel. It didn't work.

I have put manually the file in the cache location and it doesn't work either.

**Comment by alistairmcmillan** [comment]
@thenamelessthing Check the folder C:\Users\YOURUSERNAME\AppData\Local\Aerial\Temp. Is there anything in there? If there is delete it.

And which version are you trying to run. You should be running v6.1. No other version. https://github.com/cDima/Aerial/releases/tag/v6.1

**Comment by thenamelessthing** [comment]
@alistairmcmillan 

The folder C:\Users\patgag\AppData\Local\Aerial\Temp  is empty.

I also use the 6.1 version.

**Comment by alistairmcmillan** [comment]
@thenamelessthing Can you check the Event Viewer on your PC please? There will likely be entries in the Application log for Aerial.

Look for error events (the ones with the red exclamation icon) for ".NET Runtime" that say "Application: Aerial.scr" in the first line. Like the one in the screenshot below. Then copy and paste the text of the event here please. 

![2017-02-16 16_26_54-event viewer](https://cloud.githubusercontent.com/assets/125896/23030230/11a43e06-f465-11e6-8ef0-7b4d83e02e90.png)

**Comment by thenamelessthing** [comment]
Nom du journal :Application
Source :       Application Error
Date :         2017-02-16 10:49:35
ID de l’événement :1000
Catégorie de la tâche :(100)
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   T-SSO-11-003314.reseausepaq.local
Description :
Nom de l’application défaillante Aerial.scr, version : 1.0.0.0, horodatage : 0x58968453
Nom du module défaillant : KERNELBASE.dll, version : 10.0.14393.479, horodatage : 0x582588e6
Code d’exception : 0xe0434352
Décalage d’erreur : 0x0000000000017788
ID du processus défaillant : 0xe18
Heure de début de l’application défaillante : 0x01d2886c448a3e9a
Chemin d’accès de l’application défaillante : C:\WINDOWS\Aerial.scr
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : c4fbbb0c-e186-49c9-806a-53fc6460012b
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-02-16T15:49:35.842223100Z" />
    <EventRecordID>30676</EventRecordID>
    <Channel>Application</Channel>
    <Computer>T-SSO-11-003314.reseausepaq.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Aerial.scr</Data>
    <Data>1.0.0.0</Data>
    <Data>58968453</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.14393.479</Data>
    <Data>582588e6</Data>
    <Data>e0434352</Data>
    <Data>0000000000017788</Data>
    <Data>e18</Data>
    <Data>01d2886c448a3e9a</Data>
    <Data>C:\WINDOWS\Aerial.scr</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>c4fbbb0c-e186-49c9-806a-53fc6460012b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>





And



Nom du journal :Application
Source :       .NET Runtime
Date :         2017-02-16 10:49:35
ID de l’événement :1026
Catégorie de la tâche :Aucun
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   T-SSO-11-003314.reseausepaq.local
Description :
Application : Aerial.scr
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.ObjectDisposedException
   à System.Windows.Forms.Control.CreateHandle()
   à System.Windows.Forms.Form.CreateHandle()
   à System.Windows.Forms.Control.get_Handle()
   à System.Windows.Forms.Control.GetChildAtPoint(System.Drawing.Point, System.Windows.Forms.GetChildAtPointSkip)
   à ScreenSaver.IgnoreMouseClickMessageFilter.WasNotClickedOnTarget(System.Windows.Forms.Control, System.Windows.Forms.Control)
   à ScreenSaver.IgnoreMouseClickMessageFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   à System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   à System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   à System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   à System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   à System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   à ScreenSaver.Program.Main(System.String[])


XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-02-16T15:49:35.731762600Z" />
    <EventRecordID>30675</EventRecordID>
    <Channel>Application</Channel>
    <Computer>T-SSO-11-003314.reseausepaq.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application : Aerial.scr
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.ObjectDisposedException
   à System.Windows.Forms.Control.CreateHandle()
   à System.Windows.Forms.Form.CreateHandle()
   à System.Windows.Forms.Control.get_Handle()
   à System.Windows.Forms.Control.GetChildAtPoint(System.Drawing.Point, System.Windows.Forms.GetChildAtPointSkip)
   à ScreenSaver.IgnoreMouseClickMessageFilter.WasNotClickedOnTarget(System.Windows.Forms.Control, System.Windows.Forms.Control)
   à ScreenSaver.IgnoreMouseClickMessageFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   à System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   à System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   à System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   à System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   à System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   à ScreenSaver.Program.Main(System.String[])

</Data>
  </EventData>
</Event>

**Comment by thenamelessthing** [comment]
Any idea?

**Comment by alistairmcmillan** [comment]
@thenamelessthing Thanks for giving us those error events. I'm not sure what to make of them though. The important bit is the `System.ObjectDisposedException` line but I'm not sure how that could be happening when the screensaver is just starting up.

Do you have problems run other .Net applications on your system, and do they run okay?

**Comment by thenamelessthing** [comment]
...?

**Comment by chrisron95** [comment]
I see this has been closed but I just added this screensaver to my computer at work and I'm having the same "Windows Media Player encountered a problem while downloading this file". A few videos started working randomly, but the majority of the time when screensaver starts it pops up with that error.
