### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by MartinGaoR** [cDima/Aerial#46]
Hi, I used a 64 bit Windows 10 OS. When I tried to install Aerial Screen Saver. The System Screen Saver was not responding after a while. As a result the screen saver turned the whole screen dark when it was triggered. May I Know why is that so? Thank you.
![image](https://cloud.githubusercontent.com/assets/11421143/11865044/66bf5ef4-a4dc-11e5-8547-f9ec74c994c3.png)

**Comment by cDima** [comment]
Try to download the same `.scr`, but rename it to `.exe` and see if clicking on it causes it to hang as well. There may be a number of issues - slow internet may be the issue.

**Comment by MartinGaoR** [comment]
Thanks, Problem Solved. The videos are successfully loaded. It might be due to slow Internet speed. But the system screen setting remains not responding after a while. May I know what can be the cause of this issue? Thanks a lot!

**Comment by cDima** [comment]
Thanks @MartinGaoR, we'll try gracefully handling slow internet issues.
