### ISSUE TITLE
Daytime Only?

### ISSUE THREAD

**Issue by RocketSledder77** [cDima/Aerial#48]
Do matter what time of day it is even I only select night time. I only get the daytime video feeds.

**Comment by cDima** [comment]
@RocketSledder77 which locale is your system in? US English? Perhaps the time of day [logic is flawed](https://github.com/cDima/Aerial/blob/master/ScreenSaver/AerialEntities.cs#L25), or time of the machine is off:

            var time = (DateTime.Now.Hour < 6 || DateTime.Now.Hour > 19) ? "night" : "day";
            var ran = new Random();
            var links = urls.SelectMany(s => s.assets)
                .OrderBy(t => ran.Next())
                .OrderByDescending(t => settings.UseTimeOfDay && t.timeOfDay == time)
                .ToList();
