### ISSUE TITLE
Occasional Windows Media Player errors

### ISSUE THREAD

**Issue by jjunge81** [cDima/Aerial#51]
The screensaver will work fine for days, then suddenly I will get a Windows Media Player error which I will need to click and then the screensaver closes. Not sure if this has been reported before but it has happened several times. Any fix?

**Comment by alistairmcmillan** [comment]
@jjunge81 What did the error message say?

**Comment by jeffreyahallett** [comment]
It simply says that Windows Media Player encountered an error.  No error codes and no other details.  It appears as a while dialog box over a black screen.  I see it fairly regularly as well.  It happens before it plays a new segment - not during a running segment.

**Comment by sheyu921** [comment]
This occurred in my PC, too. It seems that the URL of the media files are not right, so I recommend updating the URL list constantly.

**Comment by alistairmcmillan** [comment]
@sheyu921 I'm not sure what you mean, the URLs are downloaded fresh each time you run the screensaver.

Please note down the error messages. There isn't much anyone can do to help without knowing what the error message is. :)

**Comment by sheyu921** [comment]
@alistairmcmillan   I updated a update of windows, now it work well, thanks a lot.

**Comment by jeffreyahallett** [comment]
Also, I downloaded and installed the Dec release (where the name was changed from aerial to AerialScreenSaver).  I have not seen the errors I reported previously since.  Also the caching makes the screen saver launch and segment switch much faster.

**Comment by alistairmcmillan** [comment]
@jeffreyahallett @sheyu921 glad to hear it is working now.

@jjunge81 How about you jjunge81? Is the screensaver working for you now? Are you still getting errors?

**Comment by cDima** [comment]
@jjunge81 check the latest release, perhaps it fixes the error.
