### ISSUE TITLE
The app freezes~

### ISSUE THREAD

**Issue by rayseling** [cDima/Aerial#58]
I have installed Windows Media Player in the control panel, but when I preview, the screen freezes~

**Comment by alistairmcmillan** [comment]
Could you elaborate a little? Not clear what you're saying here. Does the screensaver launch and just show the first frame of one of the videos or something else?

Also, which version of the screensaver are you running?

**Comment by cDima** [comment]
@rayseling the preview was hanging sometimes for some users, please check latest.
