### ISSUE TITLE
Error while Screensaver is active

### ISSUE THREAD

**Issue by unityhd** [cDima/Aerial#61]
Hello,

i have a Windows 10 Pro x64 and always is there a Error Message while the Screensaver is active.

Here the Error Log...
[aerial_fehlerlog.txt](https://github.com/cDima/Aerial/files/144853/aerial_fehlerlog.txt)

and the Screenshot of the Error...
![img_3117](https://cloud.githubusercontent.com/assets/6634116/13290733/532f187e-db15-11e5-8e3b-7b079cdfa60a.JPG)

**Comment by alistairmcmillan** [comment]
When the screensaver runs, if caching is enabled, it downloads the files to C:\Users\YOURUSERNAME\AppData\Local\Temp and once the download is complete it copies them to C:\Users\YOURUSERNAME\AppData\Local\Aerial.

The screensaver seems to be crashing for you on that move step. The error (translated by Google Translate) "The process can not access the file because it is being used by another process." suggests that it can't transfer the video because something else is using it in the Temp folder.

Do you have something running on your machine that might be indexing new files in that temp folder on your machine? Does the C:\Users\YOURUSERNAME\AppData\Local\Aerial folder on your machine have any files in it?

**Comment by unityhd** [comment]
I think there is the problem.
I have manually downloaded all possible *.mov and copied it to C:\Users\YOURUSERNAME\AppData\Local\Aerial. 

I have delele all *.mov files from C:\Users\YOURUSERNAME\AppData\Local\Temp so there is no conflict any more.

I hope that is the solution for the problem, i will give

**Comment by patatjenl** [comment]
Had the same error. Perhaps this English "translation" can help solve the 

Couldn't copy/paste the whole error content as the mouse was not usable while the screensaver is active. With the `tab` keys, the error wasn't selectable, either.

![aerial-error](https://cloud.githubusercontent.com/assets/756956/14043626/b16b03ac-f286-11e5-9c8c-f29b6c14e100.png)

**Comment by alistairmcmillan** [comment]
The important bit is "cannot access the file because it is being used".

Something is accessing the file so the screensaver can't move it. Nothing else should be accessing the file.

So, can you think of something on your machine that would be doing that? Accessing new files as they appear in your Temp folder?

**Comment by patatjenl** [comment]
I can think of Windows 10's Windows Defender "Real-time protection". Users cannot turn it off when no other antivirus is installed. Other than that, I don't think there is anything on this machine that should touch those files. It's a relatively new (2 weeks?) installation, too.

**Comment by alistairmcmillan** [comment]
I'm pretty sure Windows Defender only scans certain types of files. Basically anything executable like an EXE, DLL, COM, BAT file. I don't think it'd be scanning MOV files as they appear in your temp folder.

**Comment by djhmateer** [comment]
I had this error too.  I suspect it was a partially downloaded movie that caused it on a multi monitor setup.  Since downloading all the movies into the cache I've not had the issue.  I wrote about it here:  http://www.programgood.net/2016/05/24/AerialScreensaverkeyboardShortcutAndNoPowerOff.aspx

**Comment by alistairmcmillan** [comment]
@unityhd @patatjenl @djhmateer I think I know what's happening and I've put together a fix. I still want to make a couple of changes before submitting the fix to @cDima but if you feel like testing I've uploaded a version of the screensaver with the fix here. You shouldn't get the errors anymore with this version. https://github.com/alistairmcmillan/Aerial-Windows/releases/tag/4.1

**Comment by Vanhecke** [comment]
The full error, FYI.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at ScreenSaver.ScreenSaverForm.OnDownloadFileComplete(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Net.WebClient.DownloadFileOperationCompleted(Object arg)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AerialScreenSaverV3
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Joris/DOCUME~1/AERIAL~1.SCR
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AxInterop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Joris/DOCUME~1/AERIAL~1.SCR
----------------------------------------
Interop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Joris/DOCUME~1/AERIAL~1.SCR
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by alistairmcmillan** [comment]
So if you try running the new version I linked above do you still get the error?

**Comment by Vanhecke** [comment]
@alistairmcmillan I haven't seen it happen.

**Comment by SimonPriet** [comment]
[JITError.txt](https://github.com/cDima/Aerial/files/531231/JITError.txt)

I have encountered a similar error : "Unable to find a part of the path 'C:\Users\simon\AppData\Local\Temp\b2-2.mov'."

**Comment by cDima** [comment]
@unityhd @patatjenl @alistairmcmillan please check the latest version. I've refactored the caching version and made a change to the caching logic. Thanks.
