### ISSUE TITLE
Complete Download including Videos to central storage for Domain/Enterprise/Deployment Clients

### ISSUE THREAD

**Issue by mohataj** [cDima/Aerial#62]
Just a request for an installation package including all the videos and scr-preferences for all users on the machine to have the screensaver using the videos from one storage place for all users.

**Comment by cDima** [comment]
Very cool. Can we have approval from Apple?

Dmitry Sadakov
+164648531955 | http://sadakov.com

**Comment by cDima** [comment]
Closed because we cannot redistribute the videos, instead streaming them from other servers works well.
