### ISSUE TITLE
Occasional crashes in Screen Saver Settings

### ISSUE THREAD

**Issue by DanTheMan827** [cDima/Aerial#66]
I'm running Windows 10 and when I go into screen saver settings I will sometimes get a message saying "ScreenSaver has stopped working"

Sometimes it will lock up the screen saver settings (windows, not Aerial)

**Comment by alistairmcmillan** [comment]
Which version of the screensaver are you running?

**Comment by DanTheMan827** [comment]
v4

**Comment by djhmateer** [comment]
I got this issue intermittently too. For me it was the issue of partial cached downloads confusing the screensaver. After I downloaded all the movies, I haven't had this bug. I made a blogpost with more details http://www.programgood.net/2016/05/24/AerialScreensaverkeyboardShortcutAndNoPowerOff.aspx

**Comment by cDima** [comment]
@DanTheMan827 please try the v5 latest release, it may solve your issues.
