### ISSUE TITLE
It simply doesn't work for a bit

### ISSUE THREAD

**Issue by jimmyfortune** [cDima/Aerial#67]
Installing the screensaver on a windows 7 installation makes the control panel screen saver settings crash every single time again. However, the settings are saved so at least you would expect the screensaver to work, but if it does appear (cause it doesn't most of the time) it's just a photograph, not at all a video. This just proves once again what an unstable environment Windows is and how it keeps on struggling to keep track of what Mac is able to do in a very easy way. Just too bad. This application really sucks.

**Comment by jimmyfortune** [comment]
FYI... I can't even change my screensaver settings to none again as it crashes as soon as the settings box is loaded. Unbelievable

**Comment by alistairmcmillan** [comment]
1) Open c:\Windows\System32
2) Find Ribbons.scr
3) Right-click on Ribbons.scr and select Install

Ribbons will now be the default screensaver on your machine and the screensaver settings panel should stop crashing.

**Comment by jimmyfortune** [comment]
that fixes the screensaver "none" issue, but not the fact that your screensaver doesn't work at all?

**Comment by alistairmcmillan** [comment]
Just tested the screensaver on a blank virtual machine with a clean Windows 7 install. It works fine.

So the problem isn't the screensaver. The problem is the screensaver on your particular machine.
