### ISSUE TITLE
Power Settings Bug

### ISSUE THREAD

**Issue by purevertigo** [cDima/Aerial#69]
The screensaver does not allow the system to shut off the Monitor/make the monitor go to sleep after a certain time.

**Comment by alistairmcmillan** [comment]
Duplicate of #54

**Comment by djhmateer** [comment]
Slightly tangential, but if you keyboard shortcut to a 'lock screen' then you can auto power off after any length of time. I like 15mins. http://www.programgood.net/2016/05/24/AerialScreensaverkeyboardShortcutAndNoPowerOff.aspx

**Comment by purevertigo** [comment]
This is still a bug.
