### ISSUE TITLE
This application could not be started

### ISSUE THREAD

**Issue by unreqistered** [cDima/Aerial#7]
Getting this error message from the Screen Saver Setting dialog box in both Windows 7 and 8.1

This application could not be started
Do you want to view information about this issue?

Clicking YES takes me to 

https://support.microsoft.com/en-us/kb/2715633

**Comment by Neal143** [comment]
I had same issue. Installed .Net Framework 4.6 as stated in info and problem vanished.

**Comment by cDima** [comment]
Thanks @Neal143, closing and adding into a FAQ on the readme.

**Comment by unreqistered** [comment]
Nope.  Error still occurs with 4.6

**Comment by cDima** [comment]
@unreqistered did you restart? Do you have windows media player installed?

**Comment by unreqistered** [comment]
On 11/2/2015 11:07 AM, Dmitry Sadakov wrote:
>
> @unreqistered <https://github.com/unreqistered> did you restart? Do 
> you have windows media player installed?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cDima/Aerial/issues/7#issuecomment-153064562>.
>

Rebooted several times

Yes, WMP installed (stock Win 7 I believe)

**Comment by cDima** [comment]
Strange, and you followed the instructions to enable the Microsoft .NET Framework 3.5.1 as well on the microsoft issue site?

**Comment by unreqistered** [comment]
On 11/2/2015 12:35 PM, Dmitry Sadakov wrote:
>
> Strange, and you followed the instructions to enable the Microsoft 
> .NET Framework 3.5.1 as well on the microsoft issue site?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cDima/Aerial/issues/7#issuecomment-153094701>.
>
Yes
