### ISSUE TITLE
Windows HRESULT: 0xC00D10B7

### ISSUE THREAD

**Issue by zachaos** [cDima/Aerial#74]
After playing the screensaver for a while the screen goes black and I get this error. HRESULT: 0xC00D10B7. I use these for my work computers which run Windows 7. I'm in the Hospitality business so these look great. 

I did some googling to see if it was a simple fix on my end. 

This site from Microsoft:

https://msdn.microsoft.com/en-us/library/cc704587.aspx

Says:

0xC00D10B7
NS_E_WMPCORE_BUSY
Windows Media Player cannot play the file at this time. Try again later.

**Comment by cDima** [comment]
There was a caching issue it looks like. Can you recheck with the latest build?

**Comment by zachaos** [comment]
I will check it out and let you know.

Thank you, 

Zac Cannon

**Comment by JackieTseng** [comment]
I also met HRESULT:0xC00D10B7 problem.
I find my win7 system has installed .NET Framework 4.5, 4.5.1, 4.6 and 4.6.1.
How can I fix it?
Thx!
