### ISSUE TITLE
Is there a way to add my own drone videos

### ISSUE THREAD

**Issue by jbpenrod** [cDima/Aerial#76]
It would be neat for it to pull from any file in the cache. When i place a video there, it will not utilize that video whatsoever, but defaults to the Apple videos. What is telling it to grab those videos, and can I change it to grab whatever video is in the cache?

**Comment by cDima** [comment]
The cached names need to match the ones from apple, but it would be easy to add an option for your own folder of videos.

**Comment by cDima** [comment]
@jbpenrod btw the class of the project that tells it where to download video from is here - https://github.com/cDima/Aerial/blob/master/ScreenSaver/AerialEntities.cs
