### ISSUE TITLE
Dual monitor use?

### ISSUE THREAD

**Issue by yg2** [cDima/Aerial#78]
Hi there, 

Many thanks on making this, was just wondering if I could make the screensaver run across 2 monitors, making it 'think' that the 2 monitors are a single one? Instead of it showing one on each.

Thanks,
Gary

**Comment by cDima** [comment]
@yg2 Gary the screensaver would be divided in two pretty split middle, and the two monitors may be different resolutions. It works well on three monitors though, duplicating video across all three.
