### ISSUE TITLE
Preview makes the computer crash

### ISSUE THREAD

**Issue by Thanaen** [cDima/Aerial#79]
Hi there,
This screensaver looks awesome, but i cannot use it as after the installation, it takes me to a window so i can set up the screen saver, and the preview button makes the computer freeze to death (must disconnect from the session to use my computer again!).
It doesn't seem to be something that affects people, and i've checked the Q&A about troubles, and everything should be fine with my computer. I'm running the latest regular build of Windows 10!
Thanks for reading, have a nice day

**Comment by cDima** [comment]
@Thanaen very peculiar. I would check if your win10 shows videos well (.mov files) using default windows media player. And that the internet connection did not abruptly end and leave a cached corrupt version of the .mov file.

**Comment by cDima** [comment]
@Thanaen also note I'm using the latest version of the scr file on a Win10 build 14965 without issues so far.

**Comment by cDima** [comment]
@Thanaen actually this is reproducible on a clean install, I think it's to do with downloading too much video on preview... let me check.

**Comment by Thanaen** [comment]
I'll try this out right now!

**Comment by Thanaen** [comment]
Works perfectly fine! Thanks for your work! :)
