### ISSUE TITLE
Installed Successfully However Screen Goes Black If Previewed.

### ISSUE THREAD

**Issue by Neal143** [cDima/Aerial#8]
I am on Windows 7 64 bit With screen resolution of 1920 x 1080 two monitors.
I installed screensaver successfully by right clicking but nothing is shown when screensaver is started.
Does this require active internet connection to work? I am guessing from looking other comments.

Most of the time it goes in (Not Responding Mode) as shown.
![image](https://cloud.githubusercontent.com/assets/15605077/10874863/ef199436-8150-11e5-9dfb-7e52ac1d9181.png)

Thanks for the help in advance.

**Comment by cDima** [comment]
@Neal143 yes it requires an internet connection, will see why the dialog freezes, thanks.
