### ISSUE TITLE
Play different Aerial on each monitor -- doesn't

### ISSUE THREAD

**Issue by robertmeta** [cDima/Aerial#83]
Not much to add to the title, the play different aerial on each monitor, does not do so.

**Comment by chrisrlong** [comment]
current version works on 4 screens for me, different video on each one....

**Comment by robertmeta** [comment]
Let me take quick video, will ensure I am running off newest.

**Comment by cDima** [comment]
It's the 5.1 release tag, not the main page link.

**Comment by alistairmcmillan** [comment]
This was fixed in a previous release.
