### ISSUE TITLE
Suggestion: disable Travis-CI and enable AppVeyor

### ISSUE THREAD

**Issue by alistairmcmillan** [cDima/Aerial#84]
Travis-CI does support .NET applications but it uses the Mono frameworks on Ubuntu to do the builds. And Mono doesn't seem to like AxWMPLib, so Travis-CI builds of Aerial fail.

AppVeyor on the other hand does its builds on Windows. So Aerial builds quite happily without any changes. There are a handful of warning messages but the builds complete okay.

If you go here https://travis-ci.org/profile/cDima, and log in with you GitHub account you should see a green checkmark to turn off Aerial builds on Travis.

And if you go here https://ci.appveyor.com/login and log in with your GitHub account you should be presented with a list of your repositories.

**Comment by cDima** [comment]
Very good idea, will try to get this running

**Comment by cDima** [comment]
Indeed, the build works well with minor warnings - `Build success`
