### ISSUE TITLE
Allow cache location to be configurable

### ISSUE THREAD

**Issue by mikegoodspeed** [cDima/Aerial#85]
My work has my `C:\Users\` directory stored on the network and it's slow.  I think this is causing the screensaver to be unusable.  Could you allow specifying the cache location?  I'm also looking into a way to hard link the Aerial directory to a local directory to fix the problem on my end.

**Comment by cDima** [comment]
@mikegoodspeed see the https://github.com/cDima/Aerial/blob/master/ScreenSaver/Caching.cs caching file that gives the path for saving the movies, in the first lines. Change that and recompile, and it'll be hard coded to some other non-network disk. I believe that's the only location for it.
