### ISSUE TITLE
New videos

### ISSUE THREAD

**Issue by levanid** [cDima/Aerial#86]
Hi. Apple updated their aerials with 20 new videos.
Please update their path in your screensaver

**Comment by cDima** [comment]
@levanid awesome, what is the URL for the new entities? I don't see new ones at http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json - I'll have to investigate to find out.

**Comment by alistairmcmillan** [comment]
@cDima It's the same url. Note the new videos have different names like "comp_DB_D011_D009_SIGNCMP_v15_6Mbps.mov" as opposed to the previous file names that looked like "b1-1.mov".

**Comment by cDima** [comment]
Thanks @alistairmcmillan ! Checked the code - we parse the urls live from apple servers, so the new videos should be picked up well, even two videos of the top array, test for greenland:

``` 
links.Where(s => s.accessibilityLabel == "Greenland").ToArray()
{ScreenSaver.Asset[3]}
    [0]: {ScreenSaver.Asset}
    [1]: {ScreenSaver.Asset}
    [2]: {ScreenSaver.Asset}
```

So you should be able to see the new videos of Dubai and others in all  previous version of the code. @levanid is that the case?

**Comment by levanid** [comment]
Hey @cDima thanks
Yes, that is what I meant. Just wanted to double check if you parse them correctly.
Thank you

**Comment by tehloxely** [comment]
Are these new videos added now?

**Comment by alistairmcmillan** [comment]
@tehloxely There was nothing to add. The way Dmitry wrote the screensaver it should just pick up the new videos automatically. It's not doing this for you?

**Comment by tehloxely** [comment]
Oh I did get them. My bad!

**Comment by cDima** [comment]
Awesome.
