### ISSUE TITLE
Support proxy configuration documentation

### ISSUE THREAD

**Issue by jeremychild** [cDima/Aerial#87]
Currently to support a proxy I am using a config file such as `AerialScreenSaverV3.exe.config`. If you are using the scr version you will also need `AerialScreenSaverV3.scr.config`

Here is an example configuration file that allows overrides the `Proxy` set by `WebClient`.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
     <system.net>
      <defaultProxy enabled="true">
          <proxy proxyaddress="http://127.0.0.1:3128" />
     </defaultProxy>
  </system.net>
</configuration>
```
Would it be possible to add this to the documentation? If you are behind a proxy some users will not know how to configure this.

**Comment by cDima** [comment]
Great suggestion. There may be passwords and usernames, or are they
defaulted on your setup?

**Comment by alistairmcmillan** [comment]
Strangely we are behind a corporate proxy and the screensaver just works okay. Usually I have to jump through hoops to get anything to work.

Just mentioning this to point out that it works with some proxies.
