### ISSUE TITLE
3 monitor setup, W10 x64 Enterprise 1607. Weird displaying

### ISSUE THREAD

**Issue by recoi1er** [cDima/Aerial#95]
Have 3 monitors, in the settings for the screen saver if you check "Disable all but main screen on 3+ screen setups" shows a thumbnail on the left and right screens of the .mov playing on the center screen was expecting it to be turned off.

**Comment by whirly** [comment]
Got the same problem. I was wondering if this is not related to the fact that displays have different scaling settings.

**Comment by whirly** [comment]
Well I just checked the settings ; there is a "disable all but main screen", just unselect this one and it will fix your issue (which is not really an issue by the way).

**Comment by eabugda** [comment]
You can't really say that this isn't an issue, that option is there for a reason. When I have 3 different files playing at the same time on 3 different monitors, it is streaming/caching those files all at once and i get lots of stuttering video. Eventually each of the 3 videos get out of sync with one another. If I have only the main screen playing and the other 2 blacked out, it would look much better.

**Comment by recoi1er** [comment]
Eabugda to whom are you speaking to?

**Comment by cDima** [comment]
@recoi1er good find, will need to fix.
@eabugda that is a network/video card limitation... Not sure how the app would know it's video is shuttering to activate graceful degradation to a single video. Any thoughts?

**Comment by eabugda** [comment]
@cDima That's not the point I'm trying to make. The point is that when the screensaver is in single display mode, the other displays should remain blacked out, instead of displaying the thumbnail in the top left corner.

**Comment by cDima** [comment]
@eabugda yeah, that's @recoi1er's description and bug, we'll take a look.

**Comment by alistairmcmillan** [comment]
@recoi1er @whirly @eabugda Hi all, cDima has released an updated screensaver that should fix this problem for you. If you tick that option you should just get the screensaver on the primary screen and the other screens should be black. Let us know how you get on.

**Comment by eabugda** [comment]
Beautiful, thanks gang!
