### ISSUE TITLE
has a problem with Avast

### ISSUE THREAD

**Issue by zoxim** [cDima/Aerial#96]
I found that Avast's "hardened mode" causes it to fail.

**Comment by alistairmcmillan** [comment]
Do you have Avast set to "aggressive" or "moderate" mode?

**Comment by alistairmcmillan** [comment]
Submitted as a false positive here. https://www.avast.com/false-positive-file-form.php

Not sure if that relates to their hardened mode though.

**Comment by zoxim** [comment]
It fails on both Avast aggressive and moderate hardened mode here but works fine with the hardened mode turned off.

**Comment by alistairmcmillan** [comment]
@zoxim Hardened mode is only going to let things run that Avast know about and have a rating for. So until someone rates Aerial it is going to be blocked. It doesn't mean there is anything wrong with it, just that Avast don't have a rating for it.

Here you can see the screensaver scanned by 54 different anti-virus scanners. They all clear it including Avast's own anti-virus scanner. https://goo.gl/8GPpbX

The prompt that told you the screensaver was being blocked should have offered you an option to "Add an exception..." or words to that effect. That might be an option for you until someone rates Aerial in Avast's hardened mode lists.

**Comment by zoxim** [comment]
It did in fact pop up an "add an exception" when I first ran it, which I did, but hardened mode seems to block it for some reason anyway.

**Comment by cDima** [comment]
Is there a way to whitelist apple.com endpoint for the app?

**Comment by alistairmcmillan** [comment]
@cDika I don't think it's a firewall. It just blocks executables. Checks them against it's list of apps and app ratings and then decides whether to allow them to run or not.

**Comment by alistairmcmillan** [comment]
@cDima @zoxim I emailed Avast the other day and got an email today saying that the whitelist for hardened mode should be updated now so it doesn't block Aerial.

> On Mon, Jan 2, 2017 at 3:52 PM, Avast Customer Care <customer.care@avast.com> wrote:
> Hi Alistair,
> 
> Thank you for your response. I asked our virus specialists to whitelist this particular file. It now shouldn't get detected by hardened mode of Avast.
> 
> If you need further assistance, don't hesitate to contact me again.
> 
> Best Regards,
> Prokop
>  
> The Avast Support Team
> 
> Avast Software s.r.o., Enterprise Office Center, Pikrtova 1737/1A, 140 00 Prague 4, Czech Republic

@zoxim Could you try again and let us know how you get on?

**Comment by zoxim** [comment]
Yes it works in both hardened modes now. Thanks much!

**Comment by cDima** [comment]
Very awesome @alistairmcmillan , thanks!
